### ISSUE TITLE
Our Team - List page creation

### ISSUE THREAD

**Issue by jonathans199** [grammerhub-team/grammerhub-team.github.io#16]
@allantito  please gather: 
- more recent profile photos
- a brief bio
- Socials 
- A brief text for this section 

<img width="1726" alt="Screenshot 2024-11-09 at 1 32 23 PM" src="https://github.com/user-attachments/assets/babe5821-9bbe-4fce-9329-afd1ec4e571d">

**Comment by allantito** [comment]
Sent you info via DM

**Comment by jonathans199** [comment]
Info from Allan: 

**This will go under Our team:**
Our team at Grammerhub is composed of experienced mentors, educators, and industry leaders, all working together to open doors in the tech sector and foster economic empowerment for our communities.

**On pics:**
Every year, at the end of the year, we change the team to give space for some to step down and others to step up. I think for now, just leave a box for Henrique and myself. Let me know dimensions for pic.

**On socials:**
LinkedIn icon

For now, we can use name/ title but would like to do this in the future: https://beta.nyc/noel-hidalgo/

**Comment by jonathans199** [comment]
Lets leave Henrique and Allan for now

**Comment by ElvisHernandez** [comment]
This appears to be done already.
