### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by hcmlopes** [grammerhub-team/grammerhub-team.github.io#4]
## Simple header layout
- Logo
- Navigation can be initially flat however we will need to include dropdown capability within the CMS and component code
- Shopping cart (skip during initial implementation)
- Call-to-action - "Join the community"

![GRAMMERHUB_homepageArtboard 1](https://github.com/user-attachments/assets/f0d93862-618e-435d-ab8e-4842537e51f7)

**Comment by jonathans199** [comment]
Header and navigation was implemented 
<img width="1727" alt="Screenshot 2024-11-06 at 2 03 00 PM" src="https://github.com/user-attachments/assets/8e391c2c-fe1a-4544-bb6c-7d615108e47b">

Also worked on the responsive
<img width="499" alt="Screenshot 2024-11-06 at 2 03 51 PM" src="https://github.com/user-attachments/assets/856a50b4-da13-4d6c-8566-94885a2a8e05">
