### ISSUE TITLE
Create Talent Page

### ISSUE THREAD

**Issue by hcmlopes** [grammerhub-team/grammerhub-team.github.io#5]
## CMS record implementation
- Profile photo
- Name
- Title
- Description
- Skills
- Portfolio Link

## Layout implementation
Create an alternating layout showcasing all grammers that are not part of the core team. All data will be coming from the CMS record for each grammer.

![Grammerhub-Talent-For-Hire-—-GRAMMERHUB](https://github.com/user-attachments/assets/9bde97a2-fe9a-491a-b97e-dc6323fb486d)

**Comment by ElvisHernandez** [comment]
@allantito Is the image posted above representative of all the people to be listed in the talent page? Should any be removed or others added?
